In [1]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [2]:
import pandas as pd
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [19]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

1.0

In [20]:
from sklearn.model_selection import cross_val_score

In [22]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [23]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [24]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [27]:
import numpy as np
kernels= ['linear','rbf']
C=[1,10,20]
avg={}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg[kval + '_' + str(cval)]=np.average(cv_scores)

avg

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

In [28]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['linear','rbf']
    },cv=5,return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00163102, 0.00170193, 0.00102253, 0.00159507, 0.00181785,
        0.00179176]),
 'std_fit_time': array([0.00042198, 0.00027791, 0.00067755, 0.00047897, 0.00039254,
        0.00039535]),
 'mean_score_time': array([0.00113235, 0.0014545 , 0.00076566, 0.00080991, 0.00120196,
        0.00120692]),
 'std_score_time': array([0.00012645, 0.0005563 , 0.00044176, 0.0004056 , 0.00040098,
        0.00039729]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'}],


In [31]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001631      0.000422         0.001132        0.000126       1   
1       0.001702      0.000278         0.001454        0.000556       1   
2       0.001023      0.000678         0.000766        0.000442      10   
3       0.001595      0.000479         0.000810        0.000406      10   
4       0.001818      0.000393         0.001202        0.000401      20   
5       0.001792      0.000395         0.001207        0.000397      20   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.900000           0.966667                1.0   
3                1.0           0.966667           0.966667                1.0   
4                1.0           0.900000           0.933333                1.0   
5                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.973333        0.038873                4  
3         0.980000        0.016330                1  
4         0.966667        0.042164                6  
5         0.966667        0.036515                5

In [36]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1       1          rbf         0.980000
2      10       linear         0.973333
3      10          rbf         0.980000
4      20       linear         0.966667
5      20          rbf         0.966667

In [37]:
clf.best_score_

0.9800000000000001

In [38]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [41]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['linear','rbf']
    },cv=5,return_train_score=False,
                       n_iter=2)
rs.fit(iris.data,iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      20          rbf         0.966667