In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [11]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [12]:
svm =SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [33]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9265442404006677

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)


In [21]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [24]:
get_score(lr,x_train,x_test,y_train,y_test)

C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [34]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(lr,x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(svm,x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(rf,x_train,x_test,y_train,y_test))
    

C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-le

In [35]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [36]:
scores_svm


[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [37]:
scores_rf

[0.9248747913188647, 0.9532554257095158, 0.9248747913188647]

In [38]:
from sklearn.model_selection import cross_val_score


In [39]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-le

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [42]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators= 40),digits.data,digits.target)

array([0.93888889, 0.91666667, 0.94150418, 0.97493036, 0.91643454])

In [46]:
cross_val_score(RandomForestClassifier(n_estimators= 5),digits.data,digits.target)

array([0.85833333, 0.8       , 0.88579387, 0.88300836, 0.84679666])

In [47]:
cross_val_score(RandomForestClassifier(n_estimators= 100),digits.data,digits.target)

array([0.93611111, 0.93055556, 0.96100279, 0.96100279, 0.92479109])

In [48]:
cross_val_score(RandomForestClassifier(n_estimators= 75),digits.data,digits.target)

array([0.91944444, 0.92222222, 0.95821727, 0.96100279, 0.93871866])

In [49]:
cross_val_score(RandomForestClassifier(n_estimators= 60),digits.data,digits.target)

array([0.91388889, 0.925     , 0.95821727, 0.95821727, 0.92479109])