In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from word2number import w2n
from sklearn import linear_model

In [32]:
df=pd.read_excel("hiring.xlsx")
df


experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [33]:
import math
m_ts = math.floor(df.test_score.median())
m_ts

8

In [35]:
df.test_score = df.test_score.fillna(med_bed)
df.experience = df.experience.fillna('zero')
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         3.0                7   72000
7          11         7.0                8   80000

In [36]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [37]:
reg.coef_


array([3112.68912083, 1598.50652033, 2085.57108449])

In [38]:
reg.intercept_


20201.682113320523

In [42]:
reg.predict([[12,10,10],[10,9,8]])

C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([94394.72761145, 82399.70068048])

In [43]:
import pickle

In [44]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [47]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [51]:
mp.predict([[10,8,9]])

C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([82886.76524464])

In [53]:
import joblib

In [54]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [55]:
mj=joblib.load('model_joblib')

In [56]:
mj.predict([[10,8,9]])

C:\Users\Surya Teja\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([82886.76524464])